apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    component: user
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user
      project: roboshop
  template:
    metadata:
      labels:
        component: user
        project: roboshop
    spec:
      containers:
      - name: user
        image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/user:TAG
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    component: user
    project: roboshop
spec:
  selector:
    component: user
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
