componentName: user
image:
  component: user
health:
  path: /health
  port: "8080"
configMap:
  enabled: true
  data:
    REDIS_HOST: redis-master
resources:
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 500m
     memory: 512Mi